on: push
name: PHPCS

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr, phpcs
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run PHPCS
        run: phpcs -q --report=checkstyle src | cs2pr